### ISSUE TITLE
Error: Class 'Comment' not found 

### ISSUE THREAD

**Issue by AlexL777** [kongondo/Blog#34] opened 2017-03-21 01:53 UTC
Hello Developers,

I installed the ProcessBlog for the first time. I also installed the demo blog with CSS and JS. However in the front end under https://processwire.wpzweinull.ch/blog/ I get an error displayed. Class "comment" can not be found.

The error quite looks like this:

    Line 599  in /xxxxxxxxxxxxxxxx/processwire.wpzweinull.ch/site/modules/ProcessBlog/MarkupBlog.module) 

Can you help me solve the problem?

Thanks in advance.

**Comment by jik2000** [comment] 2017-05-06 12:44
Hello Alex,
I've got the same error. I got rid of the error by adding 'namespace ProcessWire' in all php files in 'site\modules\ProcessBlog' and 'site\modules\ProcessBlog\template-files' directories.
I changed first rows of php-files from
`<?php`
to
`<?php namespace ProcessWire;`

**Comment by kongondo** [comment] 2017-07-09 17:03
This seems to be a ProcessWire 3 issue but can't reproduce. Adding the namespace as suggested above is a temporary fix. Such changes will be overwritten whenever you upgrade Blog. I'm closing this for now.

**Closed by kongondo** 2017-07-09 17:03 UTC
